"""Writes the TypeScript half of the wood sets into the project.

The scripts are real `.ts` files in the `typescript/` folder next to this module. The ones
written are those whose `ns:wood_set_<name>` custom component is on a
created block, so a block only has to use a component to get its script; boats get the
boat script. `index.ts` is
built from `typescript/index.ts.template` and registers the scripts of every wood set
created so far, so creating a second set doesn't drop the first one's.
"""

from pathlib import Path
from typing import Iterable

from anvil.api.actors.actors import Entity
from anvil.api.blocks.blocks import Block
from anvil.api.core.core import CONFIG

# Relative to the project root
OUTPUT_DIRECTORY = "scripts/javascript/blocks/wood_set"

SOURCE_DIRECTORY = Path(__file__).parent / "typescript"
GENERATED_HEADER = "// Generated by anvil.kit.blocks.wood_set. Edits are overwritten on the next build.\n"

# Script -> (module, exports `register<Module>Component(init)`, exports
# `register<Module>Events()`), in output order
SCRIPTS = {
    "support": ("support", True, True),
    "togglable": ("togglable", True, False),
    "interactable": ("interactable", True, False),
    "redstone_consumer": ("redstoneConsumer", True, False),
    "strippable": ("strippable", True, True),
    "slab": ("slab", True, True),
    "sign": ("sign", True, False),
    "leaves": ("leaves", True, False),
    "sapling": ("sapling", True, False),
    "boat": ("boat", False, True),
}

# Scripts importing @minecraft/server-ui, which the manifest only declares with `scriptui`
SERVER_UI_SCRIPTS = {"sign"}

# Scripts used by every wood set created so far
_used: set[str] = set()


def generate_typescript(created: Iterable[object]) -> None:
    """Write the scripts `created` use, and earlier wood sets used, into `OUTPUT_DIRECTORY`."""
    _used.update(_scripts_used_by(created))
    used = [name for name in SCRIPTS if name in _used]

    needs_ui = sorted(SERVER_UI_SCRIPTS & set(used))
    if needs_ui and not CONFIG._SCRIPT_UI:
        raise ValueError(
            f"The wood set scripts {needs_ui} use @minecraft/server-ui. "
            "Enable 'scriptui' in anvilconfig.json, or leave out WoodBlock.SIGN and WoodBlock.HANGING_SIGN."
        )

    output = Path(OUTPUT_DIRECTORY)
    output.mkdir(parents=True, exist_ok=True)

    _write(
        output / "constants.ts",
        _read("constants.ts").replace("{{NAMESPACE}}", CONFIG.NAMESPACE),
    )
    for name in used:
        module = f"{SCRIPTS[name][0]}.ts"
        _write(output / module, _read(module))
    _write(output / "index.ts", _build_index(used))


def _scripts_used_by(created: Iterable[object]) -> set[str]:
    prefix = f"{CONFIG.NAMESPACE}:wood_set_"
    used = set()
    for block in created:
        if isinstance(block, Entity):
            used.add("boat")
        if not isinstance(block, Block):
            continue
        groups = [block.server.components, *block.server._permutations]
        for group in groups:
            for component in group:
                if component.identifier.startswith(prefix):
                    name = component.identifier.removeprefix(prefix)
                    if name not in SCRIPTS:
                        raise ValueError(
                            f"{block.identifier} uses `{component.identifier}`, which has no "
                            f"script. Add it to `SCRIPTS` in {Path(__file__).name}."
                        )
                    used.add(name)
    return used


def _build_index(used: list[str]) -> str:
    imports = []
    registrations = []
    events = []
    for name in used:
        module, has_component, has_events = SCRIPTS[name]
        title = module[0].upper() + module[1:]
        names = []
        if has_component:
            names.append(f"register{title}Component")
            registrations.append(f"\t{names[-1]}(init);")
        if has_events:
            names.append(f"register{title}Events")
            events.append(f"\t\t{names[-1]}();")
        imports.append(f'import {{ {", ".join(names)} }} from "./{module}";')

    return (
        _read("index.ts.template")
        .replace("{{imports}}", "\n".join(imports))
        .replace("{{components}}", "\n".join(registrations))
        .replace("{{events}}", "\n".join(events))
    )


def _read(file_name: str) -> str:
    return (SOURCE_DIRECTORY / file_name).read_text(encoding="utf-8")


def _write(path: Path, content: str) -> None:
    path.write_text(GENERATED_HEADER + content, encoding="utf-8", newline="\n")
